<?xml version="1.0" encoding="utf-8"?><Database Name="SQLFILM" Class="SQLFilmDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FELISSILVESTRIS\SQLEXPRESS;Initial Catalog=SQLFILM;Persist Security Info=True;User ID=sa" SettingsObjectName="Film.Properties.Settings" SettingsPropertyName="SQLFILMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ThongTinCaNhan" Member="ThongTinCaNhans">
    <Type Name="ThongTinCaNhan">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CMND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SDT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ImageByte" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ThongTinCaNhan_TbBanVe" Member="TbBanVes" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="TbBanVe" />
      <Association Name="TbQuanLyNhanSu_ThongTinCaNhan" Member="TbQuanLyNhanSu" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="TbQuanLyNhanSu" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TbQuanLyNhanSu" Member="TbQuanLyNhanSus">
    <Type Name="TbQuanLyNhanSu">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PhanQuyen" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="TbQuanLyNhanSu_ThongTinCaNhan" Member="ThongTinCaNhan" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="ThongTinCaNhan" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.TbPhim" Member="TbPhims">
    <Type Name="TbPhim">
      <Column Name="MaPhim" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhim" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TheLoai" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DaoDien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DienVien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayKhoiChieu" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MoTaPhim" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImgPhim" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="TbPhim_TbQuanLyLichChieu" Member="TbQuanLyLichChieus" ThisKey="MaPhim" OtherKey="MaPhim" Type="TbQuanLyLichChieu" />
    </Type>
  </Table>
  <Table Name="dbo.TbQuanLyLichChieu" Member="TbQuanLyLichChieus">
    <Type Name="TbQuanLyLichChieu">
      <Column Name="MaLichChieu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhim" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayChieu" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PhongChieu" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="SuatChieu" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="TbQuanLyLichChieu_TbBanVe" Member="TbBanVes" ThisKey="MaLichChieu" OtherKey="MaLichChieu" Type="TbBanVe" />
      <Association Name="TbPhim_TbQuanLyLichChieu" Member="TbPhim" ThisKey="MaPhim" OtherKey="MaPhim" Type="TbPhim" IsForeignKey="true" />
      <Association Name="TbRoom_TbQuanLyLichChieu" Member="TbRoom" ThisKey="PhongChieu" OtherKey="PhongChieu" Type="TbRoom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TbRoom" Member="TbRooms">
    <Type Name="TbRoom">
      <Column Name="PhongChieu" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SuatChieu" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="TbRoom_TbQuanLyLichChieu" Member="TbQuanLyLichChieus" ThisKey="PhongChieu" OtherKey="PhongChieu" Type="TbQuanLyLichChieu" />
    </Type>
  </Table>
  <Table Name="dbo.TbCoupon" Member="TbCoupons">
    <Type Name="TbCoupon">
      <Column Name="MaCoupon" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Member" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Voucher" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="TbCoupon_TbMember" Member="TbMembers" ThisKey="MaCoupon" OtherKey="MaCoupon" Type="TbMember" />
    </Type>
  </Table>
  <Table Name="dbo.TbMember" Member="TbMembers">
    <Type Name="TbMember">
      <Column Name="MaThanhVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CMND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCoupon" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Association Name="TbMember_TbBanVe" Member="TbBanVes" ThisKey="MaThanhVien" OtherKey="MaThanhVien" Type="TbBanVe" />
      <Association Name="TbCoupon_TbMember" Member="TbCoupon" ThisKey="MaCoupon" OtherKey="MaCoupon" Type="TbCoupon" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TbBanVe" Member="TbBanVes">
    <Type Name="TbBanVe">
      <Column Name="MaVe" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLichChieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Ghe" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GiaVe" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="MaThanhVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="TbQuanLyLichChieu_TbBanVe" Member="TbQuanLyLichChieu" ThisKey="MaLichChieu" OtherKey="MaLichChieu" Type="TbQuanLyLichChieu" IsForeignKey="true" />
      <Association Name="TbMember_TbBanVe" Member="TbMember" ThisKey="MaThanhVien" OtherKey="MaThanhVien" Type="TbMember" IsForeignKey="true" />
      <Association Name="ThongTinCaNhan_TbBanVe" Member="ThongTinCaNhan" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="ThongTinCaNhan" IsForeignKey="true" />
    </Type>
  </Table>
</Database>